language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.3
- 2.1.5
- 2.2.0
- 2.2.1
- 2.2.2
env:
  global:
  - secure: G0CLV7rqELRHQfnLNaA31r2eTcvXAVLQe7FDZZXzzZmwVNeDOo45m/hZ2E+36B3AeLtjaSWhbQn5Kr5CuSqTl2Q9gmzIrZxu7ZASA7u8aSwfo1aGqSlkoOu9D/akpQUq8P25p20CS85y1WOwlkdu2ta7OtCW2oSeLu3RX6QXzmo=
  - secure: XcQVpkJEe+C2aZ7CAEYssl3knjz+ikFRSiVtVqa9pPTfGgeNrYPAUdHRPf8+wlYmaGz/KISeRvwCHpq7weDkZbgVMspRKvwcMWeUOvuAvZSuo5VKF4CDkGVRH4CA7Px5szNpSl2JV12dwcn0FZc3KGszVT6epjxjzIaqqCHPMTU=
deploy:
  provider: rubygems
  gem: factor-connector-github
  api_key:
    secure: mMY5ZBtkbojnbXBLCnMpvdokLoJU+RbeafrQ3CZpOGXK4+mg8hoY79kdNIYNImF4bhOh3G0Ol0ByCsBGcciX1hknWLyrv8ZNNxlhoDLgTozcTIi8Zyd1SkRD360LUxGn5cDOgX+7o226zh6p2B742dVcgIf8Y469cGxT855DpBg=
  on:
    tags: true
    all_branches: true
