language: ruby
rvm:
- 1.9.3
env:
  global:
  - secure: hz+MHfMKeOgDA6JgvLZsCJEypVkOLYvE+1hih69WNIHs5Fn55zrA4xpowbUnxV8s2vMdLYWeATMmkEORy2fyn7KdiEhWAIapLpk8SnfJvCshuivZ19vB1ylHERbITGetcrP0/xiPR+wdW4L8DIFJ34uvJP27Gv3MeMTmUslLF4s=
  - secure: XcQVpkJEe+C2aZ7CAEYssl3knjz+ikFRSiVtVqa9pPTfGgeNrYPAUdHRPf8+wlYmaGz/KISeRvwCHpq7weDkZbgVMspRKvwcMWeUOvuAvZSuo5VKF4CDkGVRH4CA7Px5szNpSl2JV12dwcn0FZc3KGszVT6epjxjzIaqqCHPMTU=
