language: ruby
rvm:
- 1.9.3
env:
  global:
  - secure: ek8nwwS0Sxch6ou/6EuBEt66vBHLMJMYNNXcvE0kU964FarXEDsmDZoR/sAj4ziPN9kMykQrsZT4Hj5VLcBP9xRAIMH1zrl3vGKawWgOzndXWnd8z8UMszaDYeEIKByu+zJ+8kQQ9+kHPujQUpWlFp4sgUqOotwj5E62EmPKCPw=
  - secure: XcQVpkJEe+C2aZ7CAEYssl3knjz+ikFRSiVtVqa9pPTfGgeNrYPAUdHRPf8+wlYmaGz/KISeRvwCHpq7weDkZbgVMspRKvwcMWeUOvuAvZSuo5VKF4CDkGVRH4CA7Px5szNpSl2JV12dwcn0FZc3KGszVT6epjxjzIaqqCHPMTU=
